### ISSUE TITLE
Initial Designs

### ISSUE THREAD

**Issue by YunxinStellaWang** [MindChecker/MindChecker#4]
<img width="825" alt="screen shot 2016-03-05 at 19 11 50" src="https://cloud.githubusercontent.com/assets/13849647/13549824/2a7e392a-e306-11e5-9150-70afd11997c7.png">

**Comment by samhstn** [comment]
Nice, put this in the readme, that way everyone can see the plan

**Comment by YunxinStellaWang** [comment]
Yo Sam & Owen,

Got it, can view it :D! Thanks a lot!

On 5 March 2016 at 20:59, Sam Houston notifications@github.com wrote:

> Nice, put this in the readme, that way everyone can see the plan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MindChecker/MindChecker/issues/4#issuecomment-192735434
> .

## 

## Yunxin Stella Wang

Communication Designer
Graphic Designer
Central Saint Martins College of Arts and Design
London
